#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the PIVX network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */

static const uint8_t chainparams_seed_main[] = {
    0x25, 0x60, 0xEC, 0x3F, // 37.60.236.63
    0xB0, 0x58, 0xD8, 0x18, // 176.88.23.24
    0xC2, 0xA3, 0x8C, 0x72, // 194.163.140.114
    0xB9, 0xEF, 0xD0, 0x40  // 185.239.208.64
};

static const uint8_t chainparams_seed_test[] = {
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
