name: Compile DogeExtreme Windows 64 Wallet

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build_depends:
    name: Build Dependencies
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 \
          g++-mingw-w64-x86-64 \
          nsis \
          wine-binfmt \
          wine64

    - name: Build Dependencies
      run: |
        make -j2 -C depends HOST=x86_64-w64-mingw32

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: depends
        key: ${{ runner.os }}-depends-x86_64-w64-mingw32
        restore-keys: ${{ runner.os }}-depends-x86_64-w64-mingw32

  build_wallet:
    name: Build Wallet
    runs-on: ubuntu-20.04
    needs: build_depends
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3 \
          g++-mingw-w64-x86-64 \
          nsis \
          wine-binfmt \
          wine64

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: depends
        key: ${{ runner.os }}-depends-x86_64-w64-mingw32
        restore-keys: ${{ runner.os }}-depends-x86_64-w64-mingw32

    - name: Configure Wallet
      run: |
        ./autogen.sh
        ./configure --prefix=$PWD/depends/x86_64-w64-mingw32 --disable-dependency-tracking --with-gui=auto --enable-reduce-exports --disable-online-rust
        
    - name: Build Wallet
      run: |
        make -j2 deploy
        
    - name: Make binaries executable
      run: |
        chmod +x src/pivxd.exe
        chmod +x src/pivx-cli.exe
        chmod +x src/pivx-tx.exe
        chmod +x src/qt/pivx-qt.exe

    - name: Archive binaries
      run: |
        tar -czvf windows64.tar.gz src/pivxd.exe src/pivx-cli.exe src/pivx-tx.exe src/qt/pivx-qt.exe

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows64-build
        path: windows64.tar.gz